config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

    devise_for :users

  root  'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_flash.slim
- flash.each do |key, value|
  .alert.alert
    = value

app/views/layouts/_footer.slim
hr
  .container
    .pull-right
      = link_to 'О программе', root_path

app/views/layouts/_header.slim
nav.navbar.navbar-default
  .container
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Главная', root_path, class: 'navbar-brand'
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          = link_to 'Заявки', root_path
        - if current_user
          li.dropdown
            a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
              = current_user.email
              span.caret
            ul.dropdown-menu
              li = link_to 'Профиль', user_root_path
              li = link_to 'Настройки', edit_user_registration_path
              li.divider role="separator"
              li = link_to 'Выход', destroy_user_session_path, method: 'delete'

app/views/layouts/application.slim
doctype html
html
  head
    title Заявки

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/header'
    .container
      = render 'layouts/flash', flash: flash
      = yield
    = render 'layouts/footer'

app/views/static_pages/home.html.slim
.jumbotron
  h1 StaticPages#home
  p Find me in app/views/static_pages/home.html.slim